pipeline {
    agent any

    environment {
        GIT_CREDENTIALS = 'my-github-credentials' 
        DOCKER_REGISTRY = '192.168.100.192:5000'
        IMAGE_NAME = "${DOCKER_REGISTRY}/sample-nodejs-app"
    }

    stages {
        stage('Clone Repository') {
            steps {
                git(
                    url: 'https://github.com/kevinavicenna/ci-cd-local-testing.git',
                    credentialsId: "${GIT_CREDENTIALS}",
                    branch: 'main'
                )
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'sudo docker build -t $IMAGE_NAME ./app'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'sudo docker run --rm $IMAGE_NAME npm test'
                }
            }
        }

        stage('Push to Registry') {
            steps {
                script {
                    sh 'sudo docker push $IMAGE_NAME'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    //stop previous session & Run the new container
                    sh '''
                    sudo docker stop my-nodejs-app || true
                    sudo docker rm my-nodejs-app || true
                    '''
                    sh 'sudo docker run -d --name my-nodejs-app -p 3000:3000 $IMAGE_NAME'
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
